### ISSUE TITLE
Error while using the example code

### ISSUE THREAD

**Issue by spaul13** [ekse/code#1]
While using your toy-example code for reassembling packets and writing that into a file ( code/sec/tcp_streams_dump/main.cpp)
 I am getting the following error. Can u please tell me why I am getting this error?
**_terminate called after throwing an instance of 'Tins::pcap_error'
  what():  truncated dump file; tried to read 4 file header bytes, only got 0
before opening pcap fileAborted (core dumped)_**

**Comment by ekse** [comment]
This will happen if you run it on an empty file. Does it work if you run it on data/test.pcap?
